[global]
developmentMode = false

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
serverAddress = "127.0.0.1"

[runner]
fastReruns = true

[theme]
base = "light"
