services:
  api:
    image: hammadasher/mlops-saylani-api:latest
    container_name: mlops-api
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    image: hammadasher/mlops-saylani-frontend:latest
    container_name: mlops-frontend
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api
    restart: unless-stopped
