stages:

  download:
    cmd: python src/data_pipeline/download.py
    deps:
      - src/data_pipeline/download.py
      - params.yaml
    params:
      - data.raw_path
      - data.source_url
    outs:
      - data_and_model/raw/bank-full.csv:
          cache: true

  validate:
    cmd: python src/data_pipeline/validate.py
    deps:
      - src/data_pipeline/validate.py
      - data_and_model/raw/bank-full.csv
      - params.yaml
    params:
      - data.raw_path
      - data.sep

  clean:
    cmd: python src/data_pipeline/clean.py
    deps:
      - src/data_pipeline/clean.py
      - data_and_model/raw/bank-full.csv
      - params.yaml
    params:
      - data.raw_path
      - data.cleaned_path
      - data.sep
    outs:
      - data_and_model/processed/bank_cleaned.csv:
          cache: true

  engineer:
    cmd: python src/data_pipeline/engineer.py
    deps:
      - src/data_pipeline/engineer.py
      - data_and_model/processed/bank_cleaned.csv
      - params.yaml
    params:
      - data.cleaned_path
      - data.features_path
    outs:
      - data_and_model/features/bank_features.csv:
          cache: true

  balance:
    cmd: python src/data_pipeline/balance.py
    deps:
      - src/data_pipeline/balance.py
      - data_and_model/features/bank_features.csv
      - params.yaml
    params:
      - data.features_path
      - data.processed_dir
      - data.test_size
      - data.smote_k_neighbors
      - base.random_state
    outs:
      - data_and_model/processed/X_train_balanced.csv:
          cache: true
      - data_and_model/processed/y_train_balanced.csv:
          cache: true
      - data_and_model/processed/X_test.csv:
          cache: true
      - data_and_model/processed/y_test.csv:
          cache: true