# Streamlit Cloud Secrets
# LIVE DEPLOYMENT URLS
# Frontend: https://mlops-saylani-9deyypoxdzmnsr4wvuyshg.streamlit.app/
# Backend: https://mlops-saylani.onrender.com

# Set this to your deployed backend URL
API_URL = "https://mlops-saylani.onrender.com"

